### ISSUE TITLE
Refactor for OpenSpending Next

### ISSUE THREAD

**Issue by pwalsh** [openspending/wheredoesmymoneygo.org#13]
# Description

This is a ticket for refactoring Where Does My Money Go to bring forward to 2015. Tasks will be consolidated once the OpenSpending Next API has a prototype deploy (January 2016). List below is currently a brain dump.
# Tasks
- [ ] All API calls updated for Babbage/OpenSpending v3 API
- [ ] All vis components updated to latest work
- [ ] Consider saying bye to Jekyll. Prefer port to Lektor for various reasons (templates, possibility of simple admin for content, etc.)
